// Generated by https://quicktype.io

export interface Pageable {
  offset?: number;
  pageNumber: number;
  pageSize: number;
  paged?: boolean;
  sort?: Sort;
  unpaged?: boolean;
}

export interface Sort {
  empty: boolean;
  sorted: boolean;
  unsorted: boolean;
}
